import { Inter } from "next/font/google";
import Header from "@/app/components/Header";
import "./globals.css";
import ThemeToggle from "./components/ThemeToggle";
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"], // Adjust weights as needed
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased scroll-smooth`}
      >
            <Header />


        {children}
      </body>
    </html>
  );
}
